print ("Selamat Datang di Program Penghitung Luas Segitiga")
print ("================================================")
print ("Masukkan Alas : ")
alas = int(input())
print ("Masukkan Tinggi : ")
tinggi = int(input())
luas = alas * tinggi / 2
print ("Luas Segitiga adalah : ", luas)
print ("================================================")
print ("Terima Kasih Telah Menggunakan Program Ini")
print ("================================================")
print ("Program ini dibuat oleh :")
print ("Nama : Harfely Leipary")
print ("NIM : 12155201200033")
print ("Kelas : S1 Informatika")
print ("================================================")
print ("Program ini dibuat pada tanggal :")
print ("Tanggal : 01-07-2022")
print ("Waktu : 00:00")
print ("================================================")